// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// int_eprior
Rcpp::List int_eprior(const Eigen::MatrixXd& sx, const Eigen::VectorXd& ghat, const Eigen::VectorXd& dhat);
RcppExport SEXP Rcppsva_int_eprior(SEXP sxSEXP, SEXP ghatSEXP, SEXP dhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type sx(sxSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ghat(ghatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type dhat(dhatSEXP);
    __result = Rcpp::wrap(int_eprior(sx, ghat, dhat));
    return __result;
END_RCPP
}
