# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Integrating empirical bayesian prior function
#' by Monte Carlo integration
#'
#' @title int_eprior
#' @param sx standard data matrix
#' @param ghat estimated gamma values
#' @param dhat estimated delta values
#' @return list
#'         g.star
#'         d.star
#' @author Xin Zhou \url{xinchoubiology@@gmail.com}
int_eprior <- function(sx, ghat, dhat) {
    .Call('Rcppsva_int_eprior', PACKAGE = 'Rcppsva', sx, ghat, dhat)
}

#' SVD calculation for X=UΣV, use XtX=VtΣV to calculate the right eigen vector
#' @title arma_eigen
#' @param M input matrix = XtX
#' @return v eigen vector
#' @export
#' @author Xin Zhou \url{xinchoubiology@@gmail.com}
arma_eigen <- function(M) {
    .Call('Rcppsva_arma_eigen', PACKAGE = 'Rcppsva', M)
}

