# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Integrating empirical bayesian prior function
#' by Monte Carlo integration
#'
#' @title int_eprior
#' @param sx standard data matrix
#' @param ghat estimated gamma values
#' @param dhat estimated delta values
#' @return list
#'         g.star
#'         d.star
#' @author Xin Zhou \url{xinchoubiology@@gmail.com}
int_eprior <- function(sx, ghat, dhat) {
    .Call('Rcppsva_int_eprior', PACKAGE = 'Rcppsva', sx, ghat, dhat)
}

#' SVD calculation for X=UΣV, use XtX=VtΣV to calculate the right eigen vector
#' @title arma_eigen
#' @param M input matrix = XtX
#' @return v eigen vector
#' @export
#' @author Xin Zhou \url{xinchoubiology@@gmail.com}
arma_eigen <- function(M) {
    .Call('Rcppsva_arma_eigen', PACKAGE = 'Rcppsva', M)
}

#' Linear regression on covariate of interest when comparing with other covariates
#' @title beta_regress
#' @param M m x n expression matrix; Each row represents probes and each col means samples
#' @param pv n x B design matrix; Each col means phenotype of interest, and if B >=2, 
#'        means we have B-1 permutations on covariates of interest
#' @param svs n x (p-1) design matrix; Each row represent samples and each col means parameters
#' @param full full output or coefficient only
#' @export
#' @author Xin Zhou
beta_regress <- function(M, pv, svs, full = 0L) {
    .Call('Rcppsva_beta_regress', PACKAGE = 'Rcppsva', M, pv, svs, full)
}

